server:
  port: 8080
  context-path: /girl

person:
  name: A
  age: 18

name: B
age: 18
content: "name: ${name}, age: ${age}"

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true