server:
  port: 8080
  context-path: /girl


person:
  name: A
  age: 18
  addressList[0]:
    country: China
    provice: Hunan
    city: Yueyang
  addressList[1]:
    country: China
    provice: Hubei
    city: Wuhan

name: B
age: ${random.int[0, 100]}
content: "name: ${name}, age: ${age}"

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

debug: true
